version: '3'

services:
  pihole:
    build: .
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      - TZ=America/Sao_Paulo
      - WEBPASSWORD=${ADMIN_PASSWORD}
    restart: unless-stopped
